import { NextResponse } from "next/server";
import { createFalClient } from "@fal-ai/client";
import { isAllowedModel } from "@/lib/server/model-allowlist";
import { generationLimiter, getClientIp, rateLimitResponse } from "@/lib/server/rate-limit";
import { resolveApiKey } from "@/lib/server/resolve-keys";
import { extractApiKey } from "@/lib/server/extract-credentials";
import type { ImageGenerationRequest, ImageGenerationResponse } from "@/lib/types/generation";
import { validateImageGenerationResponse } from "@/lib/types/generation";

function resolveImageCount(value: number | undefined): number {
  if (typeof value !== "number" || !Number.isFinite(value)) return 1;
  return Math.min(4, Math.max(1, Math.floor(value)));
}

// ---------------------------------------------------------------------------
// POST /api/generate/fal
// Server-side proxy for Fal AI (FLUX) image generation.
// Accepts an optional client-provided `apiKey`; falls back to env var.
// ---------------------------------------------------------------------------

/** Map canonical aspect ratio to fal's image_size enum. */
function mapImageSize(ar: string): string {
  switch (ar) {
    case "16:9":
      return "landscape_16_9";
    case "9:16":
      return "portrait_16_9";
    case "4:3":
      return "landscape_4_3";
    case "3:4":
      return "portrait_4_3";
    default:
      return "square_hd";
  }
}

export async function POST(request: Request) {
  // --- Rate limiting ---
  const rl = generationLimiter(getClientIp(request));
  if (!rl.allowed) return rateLimitResponse(rl);

  let parsed: unknown;
  try {
    parsed = await request.json();
  } catch {
    return NextResponse.json(
      { error: "Invalid JSON body" },
      { status: 400 },
    );
  }

  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    return NextResponse.json(
      { error: "JSON body must be an object" },
      { status: 400 },
    );
  }

  const body = parsed as ImageGenerationRequest & { apiKey?: string; credentials?: { apiKey?: string } };

  // --- Resolve API key: credentials.apiKey > body.apiKey > env ---
  const clientKey = extractApiKey(body);
  const keyResult = resolveApiKey(
    clientKey,
    process.env.FAL_API_KEY,
    "Fal",
  );
  if (!keyResult.ok) {
    return NextResponse.json({ error: keyResult.error }, { status: 401 });
  }
  const apiKey = keyResult.value;

  if (
    typeof body.prompt !== "string" || !body.prompt.trim() ||
    typeof body.model !== "string" || !body.model.trim() ||
    typeof body.aspectRatio !== "string" || !body.aspectRatio.trim()
  ) {
    return NextResponse.json(
      { error: "`prompt`, `model`, and `aspectRatio` are required" },
      { status: 400 },
    );
  }

  // Strip "fal:" prefix if present.
  const apiModelId = body.model.includes(":")
    ? body.model.split(":").slice(1).join(":")
    : body.model;

  // --- Model allowlist validation ---
  if (!isAllowedModel("fal", apiModelId)) {
    return NextResponse.json(
      { error: `Invalid model: ${apiModelId}` },
      { status: 400 },
    );
  }

  try {
    const client = createFalClient({ credentials: apiKey });
    const numberOfImages = resolveImageCount(body.numberOfImages);

    const falInput: Record<string, unknown> = {
      prompt: body.prompt,
      image_size: mapImageSize(body.aspectRatio),
      num_images: numberOfImages,
    };

    if (body.guidanceScale != null) {
      falInput.guidance_scale = body.guidanceScale;
    }
    if (body.numInferenceSteps != null) {
      falInput.num_inference_steps = body.numInferenceSteps;
    }
    if (body.seed != null) {
      falInput.seed = body.seed;
    }
    if (body.safetyTolerance != null) {
      falInput.safety_tolerance = String(body.safetyTolerance);
    }
    if (body.enableSafetyChecker != null) {
      falInput.enable_safety_checker = body.enableSafetyChecker;
    }

    const result = await client.subscribe(apiModelId, { input: falInput });
    const data = result.data as { images?: { url?: string }[] } | undefined;

    // Fal returns URLs directly — no upload needed.
    const images = (data?.images ?? [])
      .map((image) => image.url)
      .filter((imageUrl): imageUrl is string => Boolean(imageUrl))
      .map((imageUrl) => ({ imageUrl }));

    if (images.length === 0) {
      return NextResponse.json(
        { error: "No image generated by Fal" },
        { status: 502 },
      );
    }

    const resp: ImageGenerationResponse = {
      imageUrl: images[0].imageUrl,
      images,
    };
    validateImageGenerationResponse(resp, "fal");
    return NextResponse.json(resp);
  } catch (err: unknown) {
    const message =
      err instanceof Error ? err.message : "Fal upstream request failed";
    console.error("[api/generate/fal] error:", err);
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
