import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import { uploadBase64ToR2 } from "@/lib/server/upload";
import { isAllowedModel } from "@/lib/server/model-allowlist";
import { generationLimiter, getClientIp, rateLimitResponse } from "@/lib/server/rate-limit";
import { resolveApiKey } from "@/lib/server/resolve-keys";
import { extractApiKey } from "@/lib/server/extract-credentials";
import {
  logGenerationRequest,
  logGenerationResponse,
} from "@/lib/server/generation-debug";
import type { ImageGenerationRequest, ImageGenerationResponse } from "@/lib/types/generation";
import { validateImageGenerationResponse } from "@/lib/types/generation";

function resolveImageCount(value: number | undefined): number {
  if (typeof value !== "number" || !Number.isFinite(value)) return 1;
  return Math.min(4, Math.max(1, Math.floor(value)));
}

// ---------------------------------------------------------------------------
// POST /api/generate/google
// Server-side proxy for Google Imagen image generation.
// Accepts an optional client-provided `apiKey`; falls back to env var.
// ---------------------------------------------------------------------------

export async function POST(request: Request) {
  // --- Rate limiting ---
  const rl = generationLimiter(getClientIp(request));
  if (!rl.allowed) return rateLimitResponse(rl);

  let body: ImageGenerationRequest & { apiKey?: string; credentials?: { apiKey?: string } };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: "Invalid JSON body" },
      { status: 400 },
    );
  }

  // --- Resolve API key: credentials.apiKey > body.apiKey > env ---
  const clientKey = extractApiKey(body);
  const keyResult = resolveApiKey(
    clientKey,
    process.env.GOOGLE_API_KEY,
    "Google",
  );
  if (!keyResult.ok) {
    return NextResponse.json({ error: keyResult.error }, { status: 401 });
  }
  const apiKey = keyResult.value;

  if (!body.prompt || !body.model || !body.aspectRatio) {
    return NextResponse.json(
      { error: "`prompt`, `model`, and `aspectRatio` are required" },
      { status: 400 },
    );
  }

  // Extract the bare model id (strip "google:" prefix if present).
  const apiModelId = body.model.includes(":")
    ? body.model.split(":").slice(1).join(":")
    : body.model;

  // --- Model allowlist validation ---
  if (!isAllowedModel("google", apiModelId)) {
    return NextResponse.json(
      { error: `Invalid model: ${apiModelId}` },
      { status: 400 },
    );
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const numberOfImages = resolveImageCount(body.numberOfImages);

    const config: Record<string, unknown> = {
      numberOfImages,
      aspectRatio: body.aspectRatio,
      outputMimeType: "image/jpeg",
    };

    if (body.seed != null) {
      config.seed = body.seed;
    }
    if (body.negativePrompt) {
      config.negativePrompt = body.negativePrompt;
    }
    if (body.enhancePrompt != null) {
      config.enhancePrompt = body.enhancePrompt;
    }
    if (body.personGeneration) {
      config.personGeneration = body.personGeneration;
    }

    const googleRequest = {
      model: apiModelId,
      prompt: body.prompt,
      config,
    };
    logGenerationRequest("POST api/generate/google", googleRequest);

    const response = await ai.models.generateImages(googleRequest);
    logGenerationResponse("POST api/generate/google", response);

    const images = await Promise.all(
      (response.generatedImages ?? [])
        .map((generatedImage) => generatedImage.image?.imageBytes)
        .filter((imageBytes): imageBytes is string => Boolean(imageBytes))
        .map(async (base64) => ({
          imageUrl: await uploadBase64ToR2(base64, "image/jpeg", "jpg"),
        })),
    );

    if (images.length === 0) {
      return NextResponse.json(
        { error: "No image generated by Google" },
        { status: 502 },
      );
    }

    const result: ImageGenerationResponse = {
      imageUrl: images[0].imageUrl,
      images,
    };
    validateImageGenerationResponse(result, "google");
    return NextResponse.json(result);
  } catch (err: unknown) {
    const message =
      err instanceof Error ? err.message : "Google upstream request failed";
    console.error("[api/generate/google] error:", err);
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
