import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import { uploadBase64ToR2 } from "@/lib/server/upload";
import { isAllowedModel } from "@/lib/server/model-allowlist";
import { generationLimiter, getClientIp, rateLimitResponse } from "@/lib/server/rate-limit";
import { resolveApiKey } from "@/lib/server/resolve-keys";
import { extractApiKey } from "@/lib/server/extract-credentials";
import type { ImageGenerationRequest, ImageGenerationResponse } from "@/lib/types/generation";

// ---------------------------------------------------------------------------
// POST /api/generate/google
// Server-side proxy for Google Imagen image generation.
// Accepts an optional client-provided `apiKey`; falls back to env var.
// ---------------------------------------------------------------------------

export async function POST(request: Request) {
  // --- Rate limiting ---
  const rl = generationLimiter(getClientIp(request));
  if (!rl.allowed) return rateLimitResponse(rl);

  let body: ImageGenerationRequest & { apiKey?: string; credentials?: { apiKey?: string } };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: "Invalid JSON body" },
      { status: 400 },
    );
  }

  // --- Resolve API key: credentials.apiKey > body.apiKey > env ---
  const clientKey = extractApiKey(body);
  const keyResult = resolveApiKey(
    clientKey,
    process.env.GOOGLE_API_KEY,
    "Google",
  );
  if (!keyResult.ok) {
    return NextResponse.json({ error: keyResult.error }, { status: 401 });
  }
  const apiKey = keyResult.value;

  if (!body.prompt || !body.model || !body.aspectRatio) {
    return NextResponse.json(
      { error: "`prompt`, `model`, and `aspectRatio` are required" },
      { status: 400 },
    );
  }

  // Extract the bare model id (strip "google:" prefix if present).
  const apiModelId = body.model.includes(":")
    ? body.model.split(":").slice(1).join(":")
    : body.model;

  // --- Model allowlist validation ---
  if (!isAllowedModel("google", apiModelId)) {
    return NextResponse.json(
      { error: `Invalid model: ${apiModelId}` },
      { status: 400 },
    );
  }

  try {
    const ai = new GoogleGenAI({ apiKey });

    const config: Record<string, unknown> = {
      numberOfImages: 1,
      aspectRatio: body.aspectRatio,
      outputMimeType: "image/jpeg",
    };

    if (body.seed != null) {
      config.seed = body.seed;
    }
    if (body.negativePrompt) {
      config.negativePrompt = body.negativePrompt;
    }
    if (body.enhancePrompt != null) {
      config.enhancePrompt = body.enhancePrompt;
    }
    if (body.personGeneration) {
      config.personGeneration = body.personGeneration;
    }

    const response = await ai.models.generateImages({
      model: apiModelId,
      prompt: body.prompt,
      config,
    });

    const base64 = response.generatedImages?.[0]?.image?.imageBytes;
    if (!base64) {
      return NextResponse.json(
        { error: "No image generated by Google" },
        { status: 502 },
      );
    }

    const imageUrl = await uploadBase64ToR2(base64, "image/jpeg", "jpg");

    const result: ImageGenerationResponse = { imageUrl };
    return NextResponse.json(result);
  } catch (err: unknown) {
    const message =
      err instanceof Error ? err.message : "Google upstream request failed";
    console.error("[api/generate/google] error:", err);
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
