import { NextResponse } from "next/server";
import { uploadBase64ToR2 } from "@/lib/server/upload";
import { isAllowedModel } from "@/lib/server/model-allowlist";
import { generationLimiter, getClientIp, rateLimitResponse } from "@/lib/server/rate-limit";
import { resolveVertexCredentials } from "@/lib/server/resolve-keys";
import { extractVertexCredentials } from "@/lib/server/extract-credentials";
import type {
  ImageGenerationRequest,
  ImageGenerationResponse,
} from "@/lib/types/generation";

// ---------------------------------------------------------------------------
// POST /api/generate/vertex
// Server-side proxy for Vertex AI Imagen image generation.
// Accepts optional client-provided vertex credentials; falls back to env vars.
// ---------------------------------------------------------------------------

export async function POST(request: Request) {
  // --- Rate limiting ---
  const rl = generationLimiter(getClientIp(request));
  if (!rl.allowed) return rateLimitResponse(rl);

  // -- Parse & validate request body --
  let body: ImageGenerationRequest & {
    vertex?: { accessToken?: string; projectId?: string; location?: string };
    credentials?: { accessToken?: string; projectId?: string; location?: string };
  };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: "Invalid JSON body" },
      { status: 400 },
    );
  }

  // --- Resolve Vertex credentials: credentials > body.vertex > env ---
  const clientVertex = extractVertexCredentials(body);
  const credResult = resolveVertexCredentials(clientVertex, {
    accessToken: process.env.VERTEX_ACCESS_TOKEN,
    projectId: process.env.VERTEX_PROJECT_ID,
    location: process.env.VERTEX_LOCATION,
  });
  if (!credResult.ok) {
    return NextResponse.json({ error: credResult.error }, { status: 401 });
  }
  const { accessToken, projectId, location } = credResult.value;

  if (!body.prompt || !body.model || !body.aspectRatio) {
    return NextResponse.json(
      { error: "`prompt`, `model`, and `aspectRatio` are required" },
      { status: 400 },
    );
  }

  // Strip "vertex:" prefix if present.
  const apiModelId = body.model.includes(":")
    ? body.model.split(":").slice(1).join(":")
    : body.model;

  // --- Model allowlist validation ---
  if (!isAllowedModel("vertex", apiModelId)) {
    return NextResponse.json(
      { error: `Invalid model: ${apiModelId}` },
      { status: 400 },
    );
  }

  // -- Build Vertex predict payload --
  const parameters: Record<string, unknown> = {
    sampleCount: 1,
    aspectRatio: body.aspectRatio,
    addWatermark: false,
  };

  if (body.seed != null) {
    parameters.seed = body.seed;
  }
  if (body.negativePrompt) {
    parameters.negativePrompt = body.negativePrompt;
  }
  if (body.enhancePrompt != null) {
    parameters.enhancePrompt = body.enhancePrompt;
  }
  if (body.personGeneration) {
    parameters.personGeneration = body.personGeneration;
  }

  try {
    const upstreamUrl = `https://${location}-aiplatform.googleapis.com/v1/projects/${projectId}/locations/${location}/publishers/google/models/${apiModelId}:predict`;

    const upstream = await fetch(upstreamUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${accessToken}`,
      },
      body: JSON.stringify({
        instances: [{ prompt: body.prompt }],
        parameters,
      }),
    });

    const data = await upstream.json();

    if (!upstream.ok) {
      // Preserve meaningful upstream error messages.
      const errMsg =
        data?.error?.message ??
        `Vertex AI returned ${upstream.status}`;
      return NextResponse.json(
        { error: errMsg },
        { status: upstream.status },
      );
    }

    const base64: string | undefined =
      data.predictions?.[0]?.bytesBase64Encoded;
    if (!base64) {
      return NextResponse.json(
        { error: "No image generated by Vertex AI" },
        { status: 502 },
      );
    }

    const mimeType: string =
      data.predictions?.[0]?.mimeType ?? "image/png";
    const ext = mimeType === "image/jpeg" ? "jpg" : "png";

    // Upload to R2 with data-URL fallback (consistent with other routes).
    const imageUrl = await uploadBase64ToR2(base64, mimeType, ext);

    const result: ImageGenerationResponse = { imageUrl };
    return NextResponse.json(result);
  } catch (err: unknown) {
    const message =
      err instanceof Error ? err.message : "Vertex upstream request failed";
    console.error("[api/generate/vertex] error:", err);
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
