"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useStudio } from "@/lib/store";
import { useSettingsStore } from "@/store/settings";
import { cn } from "@/lib/utils";
import { MODELS, STYLE_PRESETS } from "@/lib/types";
import type { AspectRatio, GeneratedImage } from "@/lib/types";
import { toast } from "sonner";
import { GoogleGenAI } from "@google/genai";
import { fal } from "@fal-ai/client";

export function PromptComposer() {
  const {
    state,
    setPrompt,
    startGeneration,
    completeGeneration,
    failGeneration,
    openApiKeyDialog,
    toggleControls,
  } = useStudio();
  const { googleApiKey, falApiKey } = useSettingsStore();

  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const [isMac, setIsMac] = useState(false);
  useEffect(() => {
    setIsMac(navigator.platform.toUpperCase().indexOf("MAC") >= 0);
  }, []);

  // Auto-focus on mount
  useEffect(() => {
    textareaRef.current?.focus();
  }, []);

  // Auto-resize helper
  function autoResize(el: HTMLTextAreaElement) {
    el.style.height = "auto";
    el.style.height = `${Math.min(el.scrollHeight, 120)}px`;
  }

  const handleGenerate = useCallback(async () => {
    if (state.provider === "google" && !googleApiKey) {
      toast.error("Google AI Studio API Key is missing");
      openApiKeyDialog();
      return;
    }
    if (state.provider === "fal" && !falApiKey) {
      toast.error("Fal AI API Key is missing");
      openApiKeyDialog();
      return;
    }
    if (!state.prompt.trim()) return;
    if (state.status === "generating") return;

    startGeneration();

    const capturedState = {
      prompt: state.prompt,
      negativePrompt: state.negativePrompt,
      aspectRatio: state.aspectRatio,
      style: state.style,
      model: state.model,
      provider: state.provider,
      guidanceScale: state.guidanceScale,
      numberOfImages: state.numberOfImages,
    };

    try {
      let finalImageUrl = "";

      // Append style to prompt if not none
      let finalPrompt = capturedState.prompt;
      if (capturedState.style !== "none") {
        finalPrompt += `, ${capturedState.style} style`;
      }

      if (capturedState.provider === "google") {
        const ai = new GoogleGenAI({ apiKey: googleApiKey });
        const response = await ai.models.generateImages({
          model: capturedState.model,
          prompt: finalPrompt,
          config: {
            numberOfImages: 1, // Only 1 for now
            aspectRatio: capturedState.aspectRatio,
            outputMimeType: "image/jpeg",
          },
        });
        
        const base64 = response.generatedImages?.[0]?.image?.imageBytes;
        if (!base64) throw new Error("No image generated by Google");
        
        // Convert base64 to Blob
        const fetchRes = await fetch(`data:image/jpeg;base64,${base64}`);
        const blob = await fetchRes.blob();
        
        try {
          const res = await fetch("/api/upload", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              fileName: `upload.jpg`,
              contentType: blob.type,
            }),
          });
          
          if (!res.ok) throw new Error("Failed to get presigned URL");
          const { url } = await res.json();
          
          const uploadRes = await fetch(url, {
            method: "PUT",
            body: blob,
            headers: { "Content-Type": blob.type },
          });
          
          if (!uploadRes.ok) throw new Error("Failed to upload to R2");
          
          finalImageUrl = url.split("?")[0];
        } catch (e) {
          console.warn("R2 upload failed, falling back to data URL", e);
          finalImageUrl = `data:image/jpeg;base64,${base64}`;
        }
        
      } else if (capturedState.provider === "fal") {
        fal.config({ credentials: falApiKey });
        
        // Map aspect ratio for fal
        let imageSize = "square_hd";
        if (capturedState.aspectRatio === "16:9") imageSize = "landscape_16_9";
        if (capturedState.aspectRatio === "9:16") imageSize = "portrait_16_9";
        if (capturedState.aspectRatio === "4:3") imageSize = "landscape_4_3";
        if (capturedState.aspectRatio === "3:4") imageSize = "portrait_4_3";

        const result = await fal.subscribe(capturedState.model, {
          input: {
            prompt: finalPrompt,
            image_size: imageSize,
            num_images: 1,
            guidance_scale: capturedState.guidanceScale,
          },
        });
        
        // @ts-ignore
        if (!result.images?.[0]?.url) throw new Error("No image generated by Fal");
        // @ts-ignore
        finalImageUrl = result.images[0].url;
      }

      const image: GeneratedImage = {
        id: crypto.randomUUID(),
        prompt: capturedState.prompt,
        negativePrompt: capturedState.negativePrompt || undefined,
        imageUrl: finalImageUrl,
        aspectRatio: capturedState.aspectRatio,
        style: capturedState.style,
        model: capturedState.model,
        provider: capturedState.provider,
        createdAt: Date.now(),
      };
      
      completeGeneration(image);
      toast.success("Image generated");
      setPrompt("");
      if (textareaRef.current) textareaRef.current.style.height = "auto";
      
    } catch (error: any) {
      console.error(error);
      failGeneration(error.message || "Failed to generate image");
      toast.error(error.message || "Generation failed");
    }
  }, [
    state,
    googleApiKey,
    falApiKey,
    startGeneration,
    completeGeneration,
    failGeneration,
    openApiKeyDialog,
    setPrompt,
  ]);

  // Keyboard shortcut: Cmd/Ctrl + Enter
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if ((e.metaKey || e.ctrlKey) && e.key === "Enter") {
        e.preventDefault();
        handleGenerate();
      }
    }
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [handleGenerate]);

  const isGenerating = state.status === "generating";
  
  // Checking active provider key
  const hasActiveKey = state.provider === "google" ? !!googleApiKey : !!falApiKey;
  const canGenerate = hasActiveKey && state.prompt.trim().length > 0 && !isGenerating;

  const modelLabel =
    MODELS.find((m) => m.value === state.model)?.label ?? state.model;
  const styleLabel =
    STYLE_PRESETS.find((s) => s.value === state.style)?.label;

  return (
    <div className="fixed inset-x-0 bottom-0 z-40 flex justify-center px-4 pb-6 pointer-events-none">
      <div
        className={cn(
          "glass-panel amber-focus pointer-events-auto w-full max-w-[720px] rounded-2xl transition-all",
          "border border-border hover:border-[rgba(245,240,235,0.1)]",
          isGenerating && "amber-pulse"
        )}
      >
        {/* Textarea */}
        <div className="px-4 pt-4 pb-2">
          <textarea
            ref={textareaRef}
            value={state.prompt}
            onChange={(e) => {
              setPrompt(e.target.value);
              autoResize(e.target);
            }}
            placeholder="Describe your vision..."
            rows={1}
            className="w-full resize-none bg-transparent text-base text-foreground placeholder:italic placeholder:text-muted-foreground focus:outline-none"
            disabled={isGenerating}
          />
        </div>

        {/* Bottom bar */}
        <div className="flex items-center justify-between gap-3 px-4 pb-3">
          {/* Quick settings chips */}
          <div className="flex items-center gap-1.5">
            <button
              type="button"
              onClick={toggleControls}
              className="rounded-md bg-surface-elevated px-2 py-1 font-mono text-[11px] text-muted-foreground transition-colors hover:text-foreground"
            >
              {state.aspectRatio}
            </button>
            <button
              type="button"
              onClick={toggleControls}
              className="rounded-md bg-surface-elevated px-2 py-1 text-[11px] text-muted-foreground transition-colors hover:text-foreground"
            >
              {modelLabel}
            </button>
            {state.style !== "none" && styleLabel && (
              <button
                type="button"
                onClick={toggleControls}
                className="rounded-md bg-surface-elevated px-2 py-1 text-[11px] text-muted-foreground transition-colors hover:text-foreground"
              >
                {styleLabel}
              </button>
            )}
          </div>

          {/* Right side */}
          <div className="flex items-center gap-2">
            <span className="hidden font-mono text-[10px] text-muted-foreground/50 sm:block">
              {isMac ? "⌘" : "Ctrl"}↵
            </span>
            {hasActiveKey ? (
              <Button
                size="sm"
                onClick={handleGenerate}
                disabled={!canGenerate}
                className={cn(
                  "gap-1.5 bg-amber text-background hover:bg-amber/90",
                  isGenerating && "animate-pulse"
                )}
              >
                <Sparkles className="size-3.5" />
                <span className="hidden sm:inline">
                  {isGenerating ? "Generating..." : "Generate"}
                </span>
              </Button>
            ) : (
              <Button
                size="sm"
                onClick={openApiKeyDialog}
                className="gap-1.5 bg-amber text-background hover:bg-amber/90"
              >
                Set API Key
              </Button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
